# Ngôn ngữ và tiêu đề website

# QUAN TRỌNG: Dòng 'baseURL' này dùng cho lúc build cuối cùng để deploy.
# Khi chạy local với `hugo server`, hãy để baseURL = "/".
# Khi build để deploy lên GitHub Pages (lệnh 'hugo'), hãy đổi thành link GitHub Pages của bạn.
# Ví dụ: baseURL = "https://Toan747912.github.io/blog_Ca_Nhan/"
baseURL = "http://localhost:1313"

languageCode = "vi-VN"
title = "Blog | Ngô Quốc Toàn"

# Xóa dòng này để không tự động tạo menu từ section
# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Trang Chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    [[menu.main]]
    name = "Profile"
    url = "/about/"
    weight = 3

# Cấu hình phân trang: 5 bài viết mỗi trang
paginate = 6

# Nơi lưu trữ thông tin cá nhân để layout có thể gọi ra
[params]
  author = "Ngô Quốc Toàn"
  description = """
  Chào mừng đến với blog của tôi!<br>
  Tôi là sinh viên <strong>Đại học Công nghệ TP.HCM</strong> ngành <strong>Công nghệ thông tin</strong> đam mê chia sẻ kiến thức về lập trình mạng, đặc biệt là với Java và JavaScript.
  """
  
  # Các liên kết mạng xã hội
  github = "https://github.com/NgoQuocToan0908"
  linkedin = "https://www.linkedin.com/in/ng%C3%B4-qu%E1%BB%91c-to%C3%A0n-b19171255/"
  
  # Ảnh đại diện profile
  avatar = "images/Avatar.jpg"

# Thêm màu chữ bàn các thẻ html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true